[project]
org-name = "ballerina"
version = "0.5.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "sql-native"
    version = "0.5.0-SNAPSHOT"
    path = "../sql-native/build/libs/sql-native-0.5.0-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["sql"]

    [[platform.libraries]]
    artifactId = "HikariCP"
    version = "3.3.1"
    path = "./lib/HikariCP-3.3.1.jar"
    groupId = "com.zaxxer"
    modules = ["sql"]
