[package]
org = "ballerina"
name = "sql"
version = "@toml.version@"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/sql-native-@project.version@.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/sql-test-utils-@project.version@.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/HikariCP-@hikkaricp.lib.version@.jar"

[[platform.java11.dependency]]
path = "./lib/hsqldb-@hsql.connector.version@.jar"
scope = "testOnly"
