[package]
org = "ballerina"
name = "sql"
version = "1.3.0"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS"]
repository = "https://github.com/ballerina-platform/module-ballerina-sql"
icon = "resources/icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
path = "../native/build/libs/sql-native-1.3.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/sql-test-utils-1.3.0-SNAPSHOT.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/HikariCP-3.3.1.jar"

[[platform.java11.dependency]]
path = "./lib/hsqldb-2.5.1.jar"
scope = "testOnly"
