[package]
org = "ballerina"
name = "sql"
version = "1.0.0"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/sql-native-1.0.0.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/sql-test-utils-1.0.0.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/HikariCP-3.3.1.jar"

[[platform.java11.dependency]]
path = "./lib/hsqldb-2.5.1.jar"
scope = "testOnly"
