[package]
org = "ballerina"
name = "sql"
version = "0.6.0-beta.3"

[[platform.java11.dependency]]
path = "../native/build/libs/sql-native-0.6.0-beta.3-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/sql-test-utils-0.6.0-beta.3-SNAPSHOT.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/HikariCP-3.3.1.jar"

[[platform.java11.dependency]]
path = "./lib/hsqldb-2.5.1.jar"
scope = "testOnly"
